### ISSUE TITLE
Inefficient

### ISSUE THREAD

**Issue by ajohnson-aerospike** [colton-aerospike/deploy-olm-ako#1]
https://github.com/colton-aerospike/deploy-olm-ako/blob/cca85c77983ec298e44b478490b28a101d892a69/setup_olm.sh#L15

Surely you could have done the awk better than this ?
awk '{if (match($6,"aerospike-kubernetes-operator") > 0) {print $7}else{print $6}}'

**Comment by colton-aerospike** [comment]
Yep, surely I could have. It's done now though :) 

https://github.com/colton-aerospike/deploy-olm-ako/commit/6efb5af5b6271077e6936a155def69f3e4a981c1
